<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2013-03-17 21:44

$extensionPath = t3lib_extMgm::extPath('replacecontent');
$extensionClassesPath = $extensionPath . 'Classes/';
return array(
	'tx_replacecontent_contentpostprocall' => $extensionClassesPath . 'ContentPostProcAll.php',
);
?>